---
global:
  scrape_interval: 2s
scrape_configs:
  - job_name: node
    scrape_interval: 1s
    static_configs:
      - targets: ['docker.for.mac.localhost:9100']
  - job_name: memery
    scrape_interval: 1s
    static_configs:
      - targets: ['docker.for.mac.localhost:8080']
